name: "Prettify Source"

on:
  push:
    branches:
      - "**"

jobs:
  prettify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
      - name: Set GitHub Actions as commit author
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actionsx/prettier@v2
        with:
          args: --check --write .
      - run: "git commit -am 'chore: Prettify repository source' || exit 0"
      - run: "git push"
